version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: /
    registries: "*"
    schedule:
      interval: weekly
  - package-ecosystem: "npm"
    directory: /
    registries: "*"
    schedule:
      interval: weekly
    open-pull-requests-limit: 15
    groups:
      dependencies:
        update-types:
          - minor
          - patch
          - major
