nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.9.2.cjs

npmRegistries:
  "https://npm.pkg.github.com":
    npmAuthToken: "${VEMPAIN_ACTION_TOKEN}"
    npmAlwaysAuth: true

npmScopes:
  vempain:
    npmRegistryServer: "https://npm.pkg.github.com"