name: CI
on:
  pull_request:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  REGISTRY_NAMESPACE: vempain
  IMAGE_NAME: ${{ github.repository }}

concurrency: build

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v5
      - name: Set up NodeJS
        uses: actions/setup-node@v5.0.0
        with:
          node-version: '22'

      - name: Test
        run: |
          yarn install
          yarn build
          yarn test --passWithNoTests --watchAll=false
        env:
          VEMPAIN_ACTION_TOKEN: ${{ secrets.VEMPAIN_ACTION_TOKEN }}

      - name: Coverage
        run: |
          yarn test:coverage
        env:
          VEMPAIN_ACTION_TOKEN: ${{ secrets.VEMPAIN_ACTION_TOKEN }}

  version-and-upload:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Check out code
        uses: actions/checkout@v5
      - name: Set up NodeJS
        uses: actions/setup-node@v5.0.0
        with:
          node-version: '22'

      - name: Get main and base version
        id: basemain
        shell: bash
        run: |
          baseVersion=$(cat VERSION)
          mainVersion=$(echo ${baseVersion} | cut -d '.' -f 1)
          echo "baseVersion=${baseVersion}" >> $GITHUB_OUTPUT
          echo "mainVersion=${mainVersion}" >> $GITHUB_OUTPUT

      - name: Generate new version
        id: newVer
        shell: bash
        run: |
          git fetch --tags origin
          currentVersion=$(git tag --list --sort=-version:refname "${baseVersion}.*" | head -n 1 || "${baseVersion}.0")

          if [ -z "${currentVersion}" ]; then
            newVersion="${baseVersion}.0"
          else
            runningNumber=$(echo ${currentVersion} | cut -f 3 -d '.')
            newVersion="${baseVersion}.$((${runningNumber} + 1))"
          fi
          echo "The generated new version is: ${newVersion}"
          echo "newVersion=${newVersion}" >> $GITHUB_OUTPUT
        env:
          baseVersion: ${{ steps.basemain.outputs.baseVersion }}

      - name: Set new package version
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/'))
        run: |
          echo "Setting version from tag: ${newVersion}"
          yarn version --immediate ${newVersion}
        env:
          newVersion: ${{ steps.newVer.outputs.newVersion }}
          VEMPAIN_ACTION_TOKEN: ${{ secrets.VEMPAIN_ACTION_TOKEN }}

      - name: Build production package
        run: |
          yarn install
          yarn build:production
        env:
          VEMPAIN_ACTION_TOKEN: ${{ secrets.VEMPAIN_ACTION_TOKEN }}

      - name: Upload package to GitHub
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/'))
        uses: actions/upload-artifact@v4
        with:
          name: "vempain-file-frontend-${{ steps.newVer.outputs.newVersion }}"
          path: dist/*
          retention-days: 30
          compression-level: 9
          overwrite: true
          if-no-files-found: warn

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image to registry
        shell: bash
        run: |
          imgName="${{ env.REGISTRY }}/${{ env.REGISTRY_NAMESPACE }}/$(echo "${{ env.IMAGE_NAME }}" | tr '[:upper:]' '[:lower:]')"
          docker build . --tag ${imgName}:latest
          echo "Setting versions to: '${mainVersion}', '${baseVersion}', '${newVersion}'"
          docker image tag ${imgName}:latest ${imgName}:${mainVersion}
          docker image tag ${imgName}:latest ${imgName}:${baseVersion}
          docker image tag ${imgName}:latest ${imgName}:${newVersion}
          docker push --all-tags ${imgName}
        env:
          mainVersion: ${{ steps.basemain.outputs.mainVersion }}
          baseVersion: ${{ steps.basemain.outputs.baseVersion }}
          newVersion: ${{ steps.newVer.outputs.newVersion }}

      - name: Create tag
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/'))
        uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.VEMPAIN_ACTION_TOKEN }}
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ steps.newVer.outputs.newVersion }}',
              sha: context.sha
            })
